### ISSUE TITLE
Need help :: Debian  compile issue:  "error call of overloaded  'TableVale(cosnt int64_t&)' is ambiguous return TableVale(entry.value.i64); "

### ISSUE THREAD

**Issue by SimonLeeHub** [alanxz/SimpleAmqpClient#239] opened 2020-06-20 05:40 UTC
GCC：v6.3.0
boost：1.53.0
rabbitmq-c：v0.10.0
cmake：3.15.0

**Comment by alanxz** [comment] 2020-06-21 20:11
Seems like a duplicate of #203 will follow up there.

**Closed by alanxz** 2020-06-21 20:11 UTC
Labels: Closed: Duplicate
